config/routes.rb
Rails.application.routes.draw do
root 'posts#index', as: 'home'

get 'about'  => 'pages#about'
resources :posts do
  resources :comments
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  validates :title, presence: true, length: {minimum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  #http_basic_authenticate_with name: "admin", password: "111",


  def create

@post = Post.find(params[:post_id])
@comment = @post.comments.create(comment_params)
redirect_to post_path(@post)

  end
  private def comment_params
    params.require(:comment).permit(:username, :body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    @heading = "Pages about us"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
http_basic_authenticate_with name: "admin", password: "111",
except: [:index, :show]

  def index
@post = Post.all
  end

  def new
@post = Post.new
  end

  def show
@post = Post.find(params[:id])
  end

  def edit
@post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if(@post.update(post_params))
    redirect_to @post
    else
      render 'edit'
      end
    end

def destroy
    @post = Post.find(params[:id])

    @post.destroy
    redirect_to posts_path
    end

  def create
#render plain: params[:post].inspects
@post = Post.new(post_params)
if(@post.save)
redirect_to @post
else
  render 'new'
  end
end


  private def post_params
params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rubyblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
      <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css' %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
    <header class="blog-header py-3">
      <div class="row flex-nowrap justify-content-between align-items-center">
        <div class="col-4 pt-1">
          <span class="link-secondary"><%= link_to "Rubyblog", home_path %> </span>
        </div>
        <div class="col-4 text-center">
          <span class="blog-header-logo text-dark"><%= link_to "Add posts", new_post_path %> </span>
        </div>
        <div class="col-4 d-flex justify-content-end align-items-center">
        
        <span class="blog-header-logo text-dark"><%= link_to "About us", about_path %> </span>
        </div>
      </div>
    </header>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1><%=@heading=%></h1>

app/views/posts/edit.html.erb
<h2>Edit post</h2>
<%= form_for :post, url: posts_path(@post), method: :patch do |f| %>
<% if @post.errors.any? %>
<% @post.errors.full_messages.each do |msg| %>
<div class="alert alert-danger"> <%= msg %>
</div>
<% end %>
<% end %>
<p>
Name<br>
<%= f.text_field(:title, {:class => 'form-control'}) %>
</p>
<p>
Text<br>
<%= f.text_area(:body, {:class => 'form-control'}) %>
</p>
<p>

<%= f.submit({:class => 'btn btn-success'}) %>
</p>

<% end %>

app/views/posts/index.html.erb
<h1> All Posts </h1>
<% @post.each do |post| %>


<div class="alert alert-light">
<h3> <%= post.title %> </h3>
<p> <%= post.body %> </p>
<%= link_to "Read next", post_path(post), :class => "btn btn-outline-primary" %>
</div>

<% end %>

app/views/posts/new.html.erb
<h2>Add new post</h2>
<%= form_for :post, url: posts_path do |f| %>
<% if @post.errors.any? %>
<% @post.errors.full_messages.each do |msg| %>
<div class="alert alert-danger"> <%= msg %>
</div>
<% end %>
<% end %>
<p>
Name<br>
<%= f.text_field(:title, {:class => 'form-control'}) %>
</p>
<p>
Text<br>
<%= f.text_area(:body, {:class => 'form-control'}) %>
</p>
<p>

<%= f.submit({:class => 'btn btn-success'}) %>
</p>

<% end %>

app/views/posts/show.html.erb
<h1> <%= @post.title %> </h1>
<p> <%= @post.body %> </p>
<hr>
<%= link_to "Edit", edit_post_path(@post), :class =>
'btn btn-warning' %>

<%= link_to "Delete", post_path(@post), method: :delete,
data: {confirm: "Are you sure?"},  :class => 'btn btn-danger' %>
<hr>
<h2> All comments </h2>
<% @post.comments.each do |comment| %>


<div class="alert alert-light">
<p><strong><%= comment.username %></strong>: <%=comment.body %></p>
</div>

<% end %>

<hr>
<h2>Add comments</h2>
<%= form_for([@post, @post.comments.build]) do |f| %>
<p>
User<br>
<%= f.text_field(:username, {:class => 'form-control'}) %>
</p>
<p>
Text comments<br>
<%= f.text_area(:body, {:class => 'form-control'}) %>
</p>
<p>

<%= f.submit("Add comments",  {:class => 'btn btn-warning'}) %>
</p>

<% end %>